### ISSUE TITLE
Shows gaps not present on my profile

### ISSUE THREAD

**Issue by ljharb** [Codennnn/Green-Wall#18]
When I generate the image for myself, there should be no gaps shown since April 2014, but I see 4 in 2022, 2 in 2021, 1 in 2019, 1 in 2018, 2 in 2017, and 1 in 2016. You can click back on my profile to verify - do note that sometimes Github messes up the history, and it recovers a few days later - so if you're caching too aggressively, that might be the issue.

Is this something you can fix?

**Comment by Codennnn** [comment]
Hi @ljharb ! 

I checked your profile and found that there are indeed the gaps you pointed out. 

![image](https://user-images.githubusercontent.com/47730755/215264007-feb20ddf-0dcd-4bc6-adc6-96b824eecd48.png)

However, when I view the same contribution graph without logging into my GitHub account,  there are no gaps display😮:

![image](https://user-images.githubusercontent.com/47730755/215264945-813ecb83-d37a-4473-9247-c048964581a4.png)

So, I think this issue is related to the GitHub Access Token. Thank you for your feedback, I will find a solution and fix that.

**Comment by ljharb** [comment]
Were you able to fix this?

**Comment by Codennnn** [comment]
To be honest, I don't know the exact cause of this problem yet...

I 'm not spending time on this project right now. When I get back into it, I will reopen this issue.

**Comment by ljharb** [comment]
Understood. Any reason not to leave it open until then?
